// Ambient module declaration for the virtual module generated by
// `vite-plugin-pwa` at build time. The plugin generates `sw.js` and exposes
// a registration helper on this virtual specifier; the type below mirrors
// the subset of the API the Hush web client uses.
//
// In vitest the module is not resolvable; src/lib/pwaUpdate.ts dynamically
// imports it inside a try/catch so the absence is non-fatal at runtime.

declare module "virtual:pwa-register" {
  export interface RegisterSWOptions {
    immediate?: boolean;
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
    onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
    onRegisterError?: (error: unknown) => void;
  }
  export function registerSW(
    options?: RegisterSWOptions,
  ): (reloadPage?: boolean) => Promise<void>;
}
